### ISSUE TITLE
[Rede x PINbank] - Dúvida consulta de transação

### ISSUE THREAD

**Issue by guilhermepinbank** [DevelopersRede/erede-java#1]
Bom dia,

Sou da empresa PINbank e estamos implementando a integração utilizando o SDK.

Tentamos efetuar a consulta de uma transação realizada, e recebemos o erro: 

**Expected a boolean but was BEGIN_OBJECT at line 1 column 445 path $.capture**

Analisando o retorno e o processamento do SDK Java, no JSON de retorno o item "capture" é um objeto, porém, o SDK Java aguarda um booleano (contido no objeto Transaction).

Outro ponto verificado: no JSON de retorno da consulta de transação, o valor da transação aparentemente está diferente do valor enviado na autorização da transação.

Foi enviado o valor 3000 (R$30,00) na autorização capturada, porém, no JSON de retorno da consulta, o SDK Java recebeu o valor 300000 (R$3.000,00).

Dados da transação capturada:

**TID: 10219042206281800076
NSU Rede: 615182142
Código de Autorização: 494152**

Trecho de código executado:

**Store store = new Store("10003366", "4175f5fbe03145a38aad1182c037a384", Environment.sandbox());
           
// Consulta transacao na Rede
Transaction transaction = (new eRede(store, LOGGER).get("10219042206281800076"));
           
if (transaction.getAuthorization() != null) {
System.out.printf("Status da transação: %s", transaction.getAuthorization().getReturnCode());
}**

Qualquer dúvida estou a disposição.

Guilherme
guilherme@pinbank.com.br

**Comment by netojoaobatista** [comment]
Olá @guilhermepinbank,

> Expected a boolean but was BEGIN_OBJECT at line 1 column 445 path $.capture

Isso foi identifidado e já está sendo resolvido.

> Foi enviado o valor 3000 (R$30,00) na autorização capturada, porém, no JSON de retorno da consulta, o SDK Java recebeu o valor 300000 (R$3.000,00).

Esse é o comportamento esperado. Se observar na documentação, a descrição do campo `amount` é:

> Valor total da transação sem separador de milhar e decimal.
> Exemplos: R$ 10,00 = 1000 | R$ 0,50 = 50

Assim, ao enviar uma requisição - seja para autorizar, capturar ou cancelar - você deve enviar:

```java
Transaction transaction = new Transaction(30.00, "ref123");
```

A assinatura do construtor é assim:

```java
public Transaction(double amount, String reference) {
  this((int) Math.round(amount * 100), reference);
}

public Transaction(int amount, String reference) {
  this.amount = amount;
  this.reference = reference;
}
```

Ou seja, caso você envie um inteiro, é esperado que você envie já sem as casas decimais; assim, ao construir o objeto `Transaction` você precisa informar `3000` como descrito na documentação. Mas caso você envie um `double`, o SDK já faz esse trabalho por você, multiplicando o valor por 100 e convertendo-o em um `int`.

**Comment by netojoaobatista** [comment]
@guilhermepinbank,

> Isso foi identifidado e já está sendo resolvido.

Por favor, faça um `git pull`. Foi criado um novo tipo para resolver essa questão. Agora o `Transaction` da requisição envia um `boolean` e o `TransactionResponse` retorna um `Capture`.

> Ou seja, caso você envie um inteiro, é esperado que você envie já sem as casas decimais;

Para facilitar o uso e tornar o SDK mais intuitivo, o `Transaction.getAmount` agora retorna um `double`.

**Comment by guilhermepinbank** [comment]
@netojoaobatista , muito obrigado pela atenção e ajuda.

Estou fazendo testes e aparentemente o SDK está multiplicando o valor por 100 2x para os dois construtores do objeto Transaction:

`  public Transaction(double amount, String reference) {
    this((int) Math.round(amount * 100), reference);
  }

  public Transaction(int amount, String reference) {
    setAmount(amount);
    setReference(reference);
  }

  public AbstractTransaction<C> setAmount(double amount) {
    this.amount = (int) Math.round(amount * 100);
    return this;
  }`

Veja que o construtor que recebe um double, multiplica o valor por 100 (tudo bem até aqui). Depois, é chamado o construtor base que utiliza o método setAmount. Este método multiplica o valor por 100 mais uma vez.

**Comment by netojoaobatista** [comment]
> Estou fazendo testes e aparentemente o SDK está multiplicando o valor por 100 2x para os dois construtores do objeto Transaction:

Você tem razão, @guilhermepinbank.

Esse defeito acaba de ser corrigido. Por favor, faça um novo teste.

```java
Store store = new Store("PV", "TOKEN", Environment.sandbox());
Transaction transaction = new Transaction(20.99, "sdk" + new Random().nextInt())
    .creditCard(
        "5448280000000007",
        "123",
        "12",
        "2020",
        "Fulano de Tal"
    );

System.out.printf("Amount antes de enviar a transação para a Rede: R$ %.02f\n",
    transaction.getAmount());

TransactionResponse transactionResponse = (new eRede(store).create(transaction));

if (transactionResponse.getReturnCode().equals("00")) {
  String tid = transactionResponse.getTid();

  System.out.printf("Amount após de enviar o pedido de autorização para a Rede: R$ %.02f\n",
      transactionResponse.getAmount());

  transactionResponse = (new eRede(store)).get(tid);

  System.out.printf("Amount após fazer uma consulta da autorização na Rede: R$ %.02f\n",
      transactionResponse.getAuthorization().getAmount());
}
```

A saída deverá ser:

```
Amount antes de enviar a transação para a Rede: R$ 20,99
Amount após de enviar o pedido de autorização para a Rede: R$ 20,99
Amount após fazer uma consulta da autorização na Rede: R$ 20,99
```
