### ISSUE TITLE
[Rede x PINbank] - Dúvida transação de débito (3DS)

### ISSUE THREAD

**Issue by guilhermepinbank** [DevelopersRede/erede-java#2]
Bom dia,

Sou da empresa PINbank e estamos implementando a integração utilizando o SDK.

Estamos tentando efetuar um teste de transação de débito utilizando o ThreeDSecure (MPI Rede).

**Estamos recebendo o seguinte erro: HTTP/1.1 400 Bad Request**

Segue abaixo a maneira que o objeto de transação é inicializado no SDK Java:

Store store = new Store("10003366", "4175f5fbe03145a38aad1182c037a384", Environment.sandbox());
      Transaction transaction = new Transaction(100, "100001").debitCard("5277696455399733", "123", "12", "2020", "Joao da Silva");
      
      ThreeDSecure threeDSecure = new ThreeDSecure();
      threeDSecure.setEmbedded(true);
      threeDSecure.setUserAgent("Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36");
      threeDSecure.setOnFailure(ThreeDSecure.DECLINE_ON_FAILURE);

      transaction.setCapture(true);
      transaction.setThreeDSecure(threeDSecure);
      transaction.addUrl(new Url("http://www.pinbank.com.br/transactions/3dsecure/success", Url.THREE_D_SECURE_SUCCESS));
      transaction.addUrl(new Url("http://www.pinbank.com.br/transactions/3dsecure/failure", Url.THREE_D_SECURE_FAILURE));
            
      transaction = (new eRede(store, LOGGER).create(transaction)); // ERRO ACONTECE NESTE PONTO

Por gentileza, podem verificar se há algo errado com a maneira que estamos utilizando o SDK para este tipo de transação?

Qualquer dúvida estou a disposição.

Guilherme
guilherme@pinbank.com.br

**Comment by netojoaobatista** [comment]
@guilhermepinbank, por favor, faça um `git pull` e, então, o seguinte teste:

```java
Store store = new Store("PV", "TOKEN", Environment.sandbox());
Transaction transaction = new Transaction(30.00, "ref123")
    .debitCard(
        "5277696455399733",
        "123",
        "12",
        "2020",
        "Fulano de Tal"
    );

transaction.addUrl("https://example.org/success", Url.THREE_D_SECURE_SUCCESS);
transaction.addUrl("https://example.org/failure", Url.THREE_D_SECURE_FAILURE);

transaction = (new eRede(store, LOGGER).create(transaction));

if (transaction.getReturnCode().equals("220")) {
  // transações com 3DS têm código de retorno 220.
  // se o retorno for 220, redirecione o cliente para a URL informada
  System.out.println(transaction.getThreeDSecure().getUrl());
}
```

O código da transação de débito foi simplificado; dessa forma, a autenticação já é configurada por padrão.

**Comment by guilhermepinbank** [comment]
Obrigado, funcionou.

Att,

Guilherme
