### ISSUE TITLE
[Rede x PINbank] - Dúvida transações negadas

### ISSUE THREAD

**Issue by guilhermepinbank** [DevelopersRede/erede-java#3]
Boa tarde,

Estou tentando forçar algumas situações, como por exemplo o código de erro 53 (enviando o valor de R$0,53), ou mesmo um cartão que não esteja autorizado a transacionar no ambiente de Sandbox.

Para todas as situações, o SDK sempre lança a exeption:

**java.lang.RuntimeException: HTTP/1.1 400 Bad Request**

Nestes casos de transação negada e com o SDK lançando a exeption, como capturamos o motivo da negativa da transação?

O código abaixo lança a exeption mencionada acima:

```
		try {
			Store store = new Store("10003366", "4175f5fbe03145a38aad1182c037a384", Environment.sandbox());
			
			Transaction transaction = new Transaction(0.53, "0100009").creditCard("5448280000000007", "123", "12", "2020", "TESTE PINBANK");
			
			TransactionResponse transactionResponse = (new eRede(store, LOGGER).create(transaction));
			
			if (transactionResponse.getReturnCode().equals("00")) {
			  System.out.printf("Transação autorizada com sucesso: %s", transactionResponse.getTid());
			}		
			
		} catch(Throwable t) {
			t.printStackTrace();
		}
```

Obs.: Não sei se este caso é passível de abertura de issue aqui no Git. Caso tenha outra maneira de eu contatar para tirar dúvidas deste tipo, me avise por favor. O suporte da Rede (ecommerce@userede.com.br) se mostrou totalmente ineficiente para tratar qualquer solicitação mais técnica relacionada ao SDK java.

Obrigado,

Guilherme

**Comment by netojoaobatista** [comment]
@guilhermepinbank, acabei de fazer um novo push; dessa vez, em vez de lançar um `RuntimeException`, será lançado um `RedeException` que conterá o `returnCode`, `returnMessage` e o respectivo `TransactionResponse`. Acredito que isso facilitará os testes negativos.

Por favor, faça um novo teste com o exemplo abaixo:

```java
Store store = new Store("PV", "TOKEN", Environment.sandbox());
Transaction transaction = new Transaction(0.53, "sdk" + new Random().nextInt())
    .creditCard(
        "5448280000000007",
        "123",
        "12",
        "2020",
        "Fulano de Tal"
    );

try {
  TransactionResponse transactionResponse = new eRede(store).create(transaction);

  if (transactionResponse.getReturnCode().equals("00")) {
    String tid = transactionResponse.getTid();

    System.out.printf("A transação %s foi autorizada com sucesso!\n", tid);
  }
} catch (RedeException e) {
  // Caso um RedeException seja lançado, um RedeError estará disponível para eventuais
  // tratamentos
  RedeError redeError = e.getRedeError();

  System.out.println("Não foi possível completar a transação.");

  if (redeError != null) {
    System.out
        .printf("Rede[%s]: %s\n", redeError.getReturnCode(), redeError.getReturnMessage());
  }
}
```

**Comment by guilhermepinbank** [comment]
Obrigado João, ficou bacana.

Implementei e fiz alguns testes. Amanhã eu faço mais testes.. inclusive com os outros tipos de transação.

Att,

Guilherme
