### ISSUE TITLE
[Rede x PINbank] - Dúvida consulta de transação por Reference Id

### ISSUE THREAD

**Issue by guilhermepinbank** [DevelopersRede/erede-java#4]
Bom dia,

No fluxo de débito, conseguimos fazer a transação e aprovar através da URL retornada no TransactionResponse (3DS MPI Rede, digitando o mesmo código gerado na página).

Conseguimos consultar a transação aprovada com sucesso.

Fazendo este mesmo fluxo de débito, mas digintando um código diferente do gerado na página (simulando uma transação negada), estamos recebendo o seguinte erro ao tentar consultar a transação: **HTTP/1.1 404 Not Found**

No trecho de código abaixo, a transação foi negada (digitado código diferente do gerado pela página):

```
		Store store = new Store("10003366", "4175f5fbe03145a38aad1182c037a384", Environment.sandbox());
		
		// Consulta transacao na Rede
		TransactionResponse transaction = (new eRede(store, LOGGER).getByReference("200002")); // Exception HTTP/1.1 404 Not Found nesta linha
		
		if (transaction.getAuthorization() != null) {
		  System.out.printf("Status da transação: %s", transaction.getAuthorization().getReturnCode());
		}	
```

Obs.: Não sei se este caso é passível de abertura de issue aqui no Git. Caso tenha outra maneira de eu contatar para tirar dúvidas deste tipo, me avise por favor. O suporte da Rede (ecommerce@userede.com.br) se mostrou totalmente ineficiente para tratar qualquer solicitação mais técnica relacionada ao SDK java.

Att,

Guilherme

**Comment by guilhermepinbank** [comment]
@netojoaobatista, tudo bem?

Sobre o caso acima, conseguiu verificar algo?

Obrigado,

Guilherme

**Comment by netojoaobatista** [comment]
@guilhermepinbank, eu não havia visto essa issue, mas também não consegui reproduzi-la.

```java
Store store = new Store("PV", "TOKEN", Environment.sandbox());

String reference = "sdk" + new Random().nextInt();
Transaction transaction = new Transaction(30, reference)
    .creditCard(
        "5448280000000007",
        "123",
        "12",
        "2020",
        "Fulano de Tal"
    );

try {
  TransactionResponse transactionResponse = new eRede(store).create(transaction);
  String tid = transactionResponse.getTid();

  // consultando por referência
  transactionResponse = new eRede(store).getByReference(reference);

  if (transactionResponse.getAuthorization().getTid().equals(tid)) {
    System.out.println("A transação foi localizada utilizando sua referência");
  }
} catch (RedeException e) {
  RedeError redeError = e.getRedeError();

  System.out.println("Não foi possível completar a transação.");

  if (redeError != null) {
    System.out
        .printf("Rede[%s]: %s\n", redeError.getReturnCode(), redeError.getReturnMessage());

  }
}
```

**Comment by guilhermepinbank** [comment]
@netojoaobatista, para reproduzir o caso mencionado:

1) Gerar uma transação de Débito:

```
try {
	Store store = new Store("10003366", "4175f5fbe03145a38aad1182c037a384", Environment.sandbox());
	
	Transaction transaction = new Transaction(25.00, "200003").debitCard("5277696455399733", "123", "12", "2020", "TESTE PINBANK");
	
	transaction.addUrl("https://www.pinbank.com.br/transactions/3dsecure/success", Url.THREE_D_SECURE_SUCCESS);
	transaction.addUrl("https://www.pinbank.com.br/transactions/3dsecure/failure", Url.THREE_D_SECURE_FAILURE);
	
	TransactionResponse transactionResponse = (new eRede(store, LOGGER).create(transaction));
	
	if (transactionResponse.getReturnCode().equals("220")) {
	  System.out.printf("Transação efetuada com sucesso: %s", transactionResponse.getThreeDSecure().getUrl());
	}		
	
} catch(Throwable t) {
	t.printStackTrace();
}
```
2) Acessar a URL devolvida dentro do atributo threeDSecure do retorno, para finalizar a transação de Débito. No exemplo acima foi gerada a URL:

https://api.userede.com.br/desenvolvedores/Redirect/auth?token=qNRlzjD9bd%2fo2i3QYmPxqkDtaGIuG9Nrajy0FLbFOYj6%2bc4cPmC7LiD45TUe9lHb8nBJvqJAmdN2Q2pROmC8OFvIfTDFT6wG1drnNCTVtOax1yHSPnMtrnBoieGiX9TUOpTOIVKp%2fEZel2lZZYdekXjx%2fd0KSDWe4bX997ZVppRZEvdkaXjylLqDQIE9tctt


3) Digitar um código diferente do gerado na página para simular a transação negada, que é o caso que a transação não está sendo encontrada na consulta por reference. Digitando o mesmo código gerado na página a transanção é aprovada, e a consulta por reference funciona Ok;

4) Efetuar a consulta da transação, utilizando o Reference enviado na criação da transação:

```
try {

	Store store = new Store("10003366", "4175f5fbe03145a38aad1182c037a384", Environment.sandbox());
	
	TransactionResponse transaction = (new eRede(store, LOGGER).getByReference("200003")); // HTTP/1.1 404 Not Found
	
	if (transaction.getAuthorization() != null) {
	  System.out.printf("Status da transação: %s", transaction.getAuthorization().getReturnCode());
	}

} catch(Throwable t) {
	t.printStackTrace();
}

```
Apenas complementando, consulta de transações negadas na modalidade crédito estão ok. Os dados da negativa são retornados corretamente.

**Comment by netojoaobatista** [comment]
Mas @guilhermepinbank, [você precisa usar a tabelinha da documentação](https://www.userede.com.br/desenvolvedores/pt/produto/e-Rede#tutorial-erros) para fazer simulação de erros. No caso de uma transação não autorizada, o valor tem que ser 0.58.

![Captura de tela de 2019-05-09 17-06-57](https://user-images.githubusercontent.com/273586/57483324-f2692900-727c-11e9-8f0c-aff01c13621c.png)


```java
Store store = new Store("PV", "TOKEN", Environment.sandbox());

String reference = "ft-1";
boolean exists = false;

try {
  TransactionResponse transactionResponse = new eRede(store).getByReference(reference);
  Authorization authorization = transactionResponse.getAuthorization();

  System.out.printf("A transação %s já existe. Seus dados são:\n\n", reference);
  System.out.printf("TID: %s\n", authorization.getTid());
  System.out.printf("NSU: %s\n", authorization.getNsu());
  System.out.printf("Authorization Code: %s\n", authorization.getAuthorizationCode());
  System.out.printf("Amount: %s\n", authorization.getAmount());
  System.out.printf("Ela foi autorizada? %s\n",
      authorization.getReturnCode().equals("00") ? "Sim" : "Não");

  // se ela já existe, não precisamos criá-la novamente
  exists = true;
} catch (RedeException re) {
  // se a transação não existir, uma exceção será disparada e seu
  // código será 78.
  // ...
}

// se ela não existe ainda, precisamos criá-la
if (!exists) {
  System.out.printf("A transação %s ainda não existe ainda. Vamos criá-la...\n\n", reference);

  try {
    Transaction transaction = new Transaction(0.58, reference)
        .debitCard(
            "5277696455399733",
            "123",
            "12",
            "2020",
            "Fulano de Tal"
        );

    transaction.addUrl("https://example.org/success", Url.THREE_D_SECURE_SUCCESS);
    transaction.addUrl("https://example.org/failure", Url.THREE_D_SECURE_FAILURE);

    TransactionResponse transactionResponse = new eRede(store).create(transaction);

    if (transactionResponse.getReturnCode().equals("220")) {
      System.out.printf("A transação foi criada; redirecione seu cliente para:\n%s\n",
          transactionResponse.getThreeDSecure().getUrl());
    }
  } catch (RedeException e) {
    RedeError redeError = e.getRedeError();

    System.out.println("Não foi possível completar a transação.");

    if (redeError != null) {
      System.out
          .printf("Rede[%s]: %s\n", redeError.getReturnCode(), redeError.getReturnMessage());

    }
  }
}
```

**Comment by guilhermepinbank** [comment]
Tranquilo @netojoaobatista , esse tipo de teste eu simulei.

Eu gostaria de simular o teste da transação de débito não ser autorizada no banco do cliente por exemplo, durante o fluxo do 3dSecure, e não no fluxo da criação da transação.

A transação foi criada normalmente, retornou o código 220. Se eu aprovar a transação digitando o mesmo código gerado na página, consigo consultá-la normalmente. Se eu digitar um código diferente, recebo um Not Found na consulta.

Uma transação de débito neste cenário, não deveria retornar na consulta, da mesma maneira que as outras transações negadas ou aprovadas?

**Comment by netojoaobatista** [comment]
> Eu gostaria de simular o teste da transação de débito não ser autorizada no banco do cliente por exemplo, durante o fluxo do 3dSecure, e não no fluxo da criação da transação.

Mas é justamente no fluxo do 3ds que a não autorização vai acontecer. Se você colocar o valor `0.58`, ele vai gerar a URL de autenticação, o cliente vai autenticar e, então, você vai conseguir consultar a transação e receber o erro 58.

Todo teste negativo que for fazer no sandbox, você precisa usar a tabelinha de erros.

**Comment by guilhermepinbank** [comment]
@netojoaobatista, desculpe pela confusão. Entendi o fluxo do teste de negativas para as transações de Débito.

Obrigado.
